#!/bin/bash
# Download real retro gaming content

echo "==================================================="
echo "Retro Gaming Content Sources"
echo "==================================================="
echo ""
echo "Option 1: Archive.org Gaming Videos"
echo "---------------------------------------------------"
echo "Search: https://archive.org/details/classicpcgames"
echo "Search: https://archive.org/details/softwarelibrary_msdos_games"
echo ""
echo "Option 2: YouTube with yt-dlp"
echo "---------------------------------------------------"
echo "Search YouTube for:"
echo "  - 'NES gameplay 8-bit'"
echo "  - 'Super Mario Bros speedrun'"
echo "  - 'Pac-Man arcade gameplay'"
echo "  - 'Tetris GB gameplay'"
echo "  - 'Space Invaders original'"
echo ""
echo "Download with:"
echo "  yt-dlp -f 'worstvideo' 'https://www.youtube.com/watch?v=VIDEO_ID'"
echo ""
echo "Option 3: Free Pixel Art / Sprite Sheets"
echo "---------------------------------------------------"
echo "- OpenGameArt.org - https://opengameart.org/"
echo "- Kenney.nl - https://kenney.nl/assets (free game assets)"
echo "- itch.io - Search 'pixel art sprite'"
echo ""
echo "Option 4: Convert with our tool"
echo "---------------------------------------------------"
echo "Once you have a video file:"
echo "  python3 dither_video.py your_game.mp4 output_dithered.mp4"
echo "  python3 video_streamer.py output_dithered.mp4 --brightness 0.3 --loop"
echo ""
echo "==================================================="
echo "The animations I created are original, not real game footage."
echo "They're designed to look like the games but are simplified."
echo "==================================================="
